### PR TITLE
Fix issue where app fails to load when no devices are present

### LINKED ISSUE #21: App crashes and doesn't load if no MIDI devices are found
The PR should include tests, of course.

### PR DESCRIPTION
**Pull request by sleexyz**
Closes #21

### CODE REVIEW

File: gallium-live/src/Editor.js [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+  isPlaying: boolean,
+  output: { send: (any, number) => void },
+  beat: number,
+  pattern: Pattern<*>
+};
+
+export const globalPlaybackState: PlaybackState = {
+  isPlaying: false,
+  output: {
+    send: console.log
```
Comment (sleexyz) [inline gallium-live/src/Editor.js]: dummy, instead of console.log
